function getURLParameter(name) {
	return decodeURI(
		(RegExp(name + '=' + '(.+?)(&|$)').exec(location.search)||[,null])[1]
	);
}

var firstApd = '<div class="apdOuter"><div class="container tableDiv"><div class="middle"><div class="apdInner"><!--div class="control rel"><div class="btn" style="position:absolute; left:-120px;"><img src="img/btns/leftBtn.png"></div><div class="btn" style="position:absolute; right:-120px;"><img src="img/btns/rightBtn.png"></div></div--><div class="talker_apd"></div></div><!-- apdInner --></div></div></div>';

var talkersArr = ['<div class="talker clearfix"><div class="head"><div class="img"> <a href="https://www.facebook.com/jonathan.liao.18"><img width="240" src="img/talkers/廖哲毅.jpg"></a></div><h3>廖哲毅</h3><h4 class="exp"><a href="https://www.facebook.com/weare1987?ref=stream&hc_location=timeline">壹玖八七工作室</a><br>創作人/製作人/戲劇導演</h4></div><div class="info"><p class="stone">如果你想要比別人更早體驗領航者的滋味，你就要有勇氣接受比別人多更多的障礙與挑戰。</p><div class="intro"><p>初次見面會被他帥氣的外表與身高所吸引。在台大戲劇系畢業後，廖哲毅走上導演之路，並且與一群志同道合的夥伴成立「壹玖八七」網站與工作室。然而，「壹玖八七」的夢想更大更遠。</p><p>2013年下半年即將上映的「時下暴力」，便是「壹玖八七」的作品。儘管嘗試呈現的是有關社會議題的內容，但不同於一般的紀錄片，該電影更有自身的關懷。此外，哲毅也想要打破不同於過去電影製作單打獨鬥的模式，改採合作的方式來進行。或許也因為如此，哲毅總是非常謙虛地希望將所有的努力歸給團隊裡所有的人，而非他自己。</p><p>對他來說，這個夢想是屬於大家的。在未來，他也希望「壹玖八七」可以為台灣社會與藝文界做更多的貢獻，將更多故事以各種不同的媒介形式展現給所有人。</p></div></div></div><!-- talker -->' 
,'<div class="talker clearfix"><div class="head"><div class="img"><img width="240" src="img/talkers/洪智杰.jpg"></div><h3>洪智杰</h3><h4 class="exp"><a href="http://wp.friendshipcit.org/">至善社會福利基金會</a>執行長</h4></div><div class="info"><p class="stone">「只有愛是不夠的，還要知道如何行動」</p><div class="intro"><p>如果你想參與國際ＮＧＯ、想透過國際型組織來增加自己對周遭環境、社會世界的關注、或者想透過國際ＮＧＯ開展行動，你覺得最需要的可能會是什麼？是專業知識？還是時間？還是無私的奉獻？在過去幾年進行國際援助的經驗與行動過程中，洪智杰認為除了愛之外，我們還需要知道如何去行動。「我們都在學習愛的這條路上。」</p></p><p>至善基金會的成立到洪智杰擔任執行長，在台灣的原鄉部落、越南、雲南等地，在服務的過程中學習如何愛，也學習如何實踐愛，不分文化、國界提供協助，完成使命。</p><p>智杰將分享在國際援助時所面對的困難與挑戰，以及克服這些問題的方法與故事。因為，有了想法還不夠，更重要的是要知道如何行動！</p></div></div></div><!-- talker -->' 
,'<div class="talker clearfix"><div class="head"><div class="img"><img width="240" src="img/talkers/金惟純.jpg"></div><h3>金惟純</h3><h4 class="exp"><a href="http://www.businessweekly.com.tw/">商業周刊</a>創辦人、<br>商業周刊榮譽發行人</h4></div><div class="info"><p class="stone">「真」到極致，會產生力量！</p><div class="intro"><p>第一次拜訪金惟純先生，就被這句話震懾！金惟純先生所謂的「玩真的」，不只是行動上的真，原來他講的還有念頭上的真。「真的念頭會讓事情發生。」</p><p>在童年的時候，金惟純先生最大的夢想就是擺脫母親的管束。這種對於自由的追求，在之後進入社會以及面對挫折時，都產生了很大的幫助。每一次的行動固然都很重要，但時刻回過頭來檢視那個促使行動的想法也是非常需要的。「隨時回過頭去看自己想法的真／假」，將有機會促使更多的行動與實踐。</p><p>想法（idea）不是活的，「人」才是活的。在年輕時代，無論基於什麼原因，我們都要「假戲真做」，把一開始也許是的「妄想」，變成為各種嘗試性的行動，開啓並累積更多的正向力。</p></div></div></div><!-- talker -->' 
,'<div class="talker clearfix"><div class="head"><div class="img"><a href="https://www.facebook.com/littlesweetfields"><img width="240" src="img/talkers/許峰源.jpg"></a></div><h3>許峰源</h3><h4 class="exp"><a href="http://www.fayu.com.tw/">法羽律師事務</a>所所長、<br><a href="http://www.tw-bathroom.info/"> 凱撒衛浴獨立</a>董事</h4></div><div class="info"><p class="stone">心的強大，才是真正的強大</p><div class="intro"><p>應屆考上律師、一畢業就開設律師事務所，是台灣唯一一家專攻保險理賠領域。除了律師身份之外，許峰源更投身於他渴望的寫作、說話，追求生活的自由，真正實踐「年輕，不打安全牌」的理念。有別於一般人，特殊的生命經歷帶給許峰源更多磨練，讓他更積極與努力，比別人能夠較早享受果實。然而，在這背後所失去的可能是認識真實自我的機會。當經歷原有人生目標消失的劇烈變化後，他開始反思，並且決定踏入全新的領域，為自己的生命創造更多的機會。</p></div></div></div><!-- talker -->' 
,'<div class="talker clearfix"><div class="head"><div class="img"><img width="240" src="img/talkers/夢.jpg"></div><h3>黃威愷、胡庭碩</h3><h4 class="exp"><a href="http://setour.org/">尋找一個公平的夢</a>計劃發起人</h4></div><div class="info"><p class="stone">要改變世界，不是一個人做了很多，而是每個人都做了一點點</p><div class="intro"><p>大學念到一半，毅然決然休學。從台灣到埃及，翻越高山，穿過沙漠，橫跨了四分之一地球的距離。把世界當成老師，以土地作為教室，拜訪了當地30位具有理想及實踐力的社會企業家，不只帶回來許多精彩的故事，更帶回來了夢想與勇氣。在旅程之後，他們想以更具體的行動來影響改變社會。這個未來的計劃與行動很大，但也很簡單。讓我們一起來感受他們的熱情與實踐想法的勇氣。</p><p>我們每一個人都有夢想，我們每一個人也都有實現夢想的能力。</p></div></div></div><!-- talker -->' 
,'<div class="talker clearfix"><div class="head"><div class="img"><img width="240" src="img/talkers/吳佳玲.jpg"></div><h3>吳佳玲</h3><h4 class="exp"><a href="https://www.facebook.com/littlesweetfields">宜蘭小田田</a> 田間管理員</h4></div><div class="info"><p class="stone">讓大家用自己的眼睛來認證，認識耕作的過程，這種方式可以跳脫農產品是一種商品的邏輯，拉近生產者跟消費者之間的距離。</p><div class="intro"><p>天、地、人三者間相互調和的關係，在農田實作裡可以感受到最深。作為現代人，我們經常面臨的是緊張、焦慮、壓力與競爭。在這些不斷積累的負面能量裡，我們忘了與自己建立關係，也忘了與自然，忘了與每天腳踏著的大地建立連結。我們的身體逐漸消失在虛擬世界之中，我們漸漸感受不到自己。</p><p>「我的成就感來自於看到稻子成長時的感動」，吳佳玲的眼神突然奮而有神地說著。研究所念到一半，決定休學參與友善耕作，與一群同樣年輕的夥伴成立了「宜蘭小田田」，希望透過親身實作的方式來推廣友善耕作。他們不像農村裡大多數年長的農人，他們是年輕、積極參與關心社會議題的台灣青年人。從小討厭農村的佳玲，沒想到在長大後會投入農事。她堅定地認為，「農事是具有前瞻性的」。人生有很多條路，但選擇最少人走的那一條路，也許艱苦、但卻會是收獲最多的。</p></div></div></div><!-- talker -->' 
,'<div class="talker clearfix"><div class="head"><div class="img"><img width="240" src="img/talkers/崔愫欣.jpg"></div><h3>崔愫欣</h3><h4 class="exp"><a href="http://www.gcaa.org.tw/">綠色公民行動聯盟</a>秘書長</h4></div><div class="info"><p class="stone">有些變化是一點一滴的，像是看到人的變化、社會的變化，就是這些東西會讓我保持熱情想要繼續堅持下去。</p><div class="intro"><p>在求學時代曾以《貢寮，你好嗎？》紀錄片而活躍於影像記錄與關懷社會議題的領域，崔愫欣對紀錄片拍攝有獨特的想法。一開始因為無法以言語跟家人溝通有關社會的議題，她選擇了以紀錄片的方式來向周圍的人傳遞訊息。然而，她更想重視的是，在紀錄片放映時的那種「人與人之間的交流」。在2011年日本核災事件之後，離婚率、結婚率，以及寫遺書的比例都有顯著上升。「這是一個時代的大轉變」，當我們對災難的看法改變了，我們也改變了看待自己與他人的方式。這是她的熱情來源。當她藉由「流浪者計劃」重新獲得能量之後，選擇繼續投入環境保護運動，並且希望能夠在台灣建立一個成熟、穩定的NGO平台，讓有理想、有熱情的年輕人，有機會有場域可以投入、可以發揮，同時也希望開啓更多的行動。</p></div></div></div><!-- talker -->' 
,'<div class="talker clearfix"><div class="head"><div class="img"><img width="240" src="img/talkers/彭蒙惠.jpg"></div><h3>彭蒙惠(Doris)</h3><h4 class="exp">《<a href="http://digichannel.go2school.com.tw/lt/main.asp">大家說英語</a>》、《<a href="http://www.studioclassroom.com/default.php">空中英語教室</a>》與《彭蒙惠英語》雜誌創辦人</h4></div><div class="info"><p class="stone">如果沒有一個人會跟你走同樣的路 你就該選擇你應該走的路</p><div class="intro"><p>1950年來到台灣，彭蒙惠貢獻了60年時光在這塊異鄉的土地上。我們從小閱讀的《大家說英語》與《空中英語教室》，都是她一手建立，對台灣的英語教育有很大的貢獻。親力親為數十載，她對台灣這塊土地有了深厚的感情，對於教育的熱情更是不遺餘力。她認為自己不僅是台灣人，也是賽德克族。基於信仰，她願意透過不間斷地實踐來向所有人證明，好的想法就應該努力行動，而且應該堅持下去。一直到現在，她依然繼續著當初正在做的事情，也希望能夠用她的故事來召喚更多的行動。</p></div></div></div><!-- talker -->' 
,'<div class="talker clearfix"><div class="head"><div class="img"><img width="240" src="img/talkers/季淳.jpg"></div><h3>季淳</h3><h4 class="exp">美國西方文理大學政治系教授<br>台灣書院推手</h4></div><div class="info"><p class="stone">未來的世界可大可小，你的心思有多高遠，有多遼闊，你未來的世界就有多大。</p><div class="intro"><p>三年前利用職務上的假期回到台灣，就立即投入於推動大學裡的住宿學習與書院（博雅）教育。即使困難重重，但他認為好的想法就應該要盡力實踐。季淳目前為政治大學國際發展書院總導師，對他來說，大學應該是教大學問，而非職業訓練所；大學要培養的人才是通才，而非專才。此外，在美國教書的他也強調，「國際化」與「多元化」並非要出國才能學習，平時就需要培養對多元文化的包容、適應與欣賞能力。儘管博雅教育的成效並非立竿見影，但他相信，只要認同某個核心與信念，就要放手去做。</p></div></div></div><!-- talker -->'
,'<div class="talker clearfix"><div class="head"><div class="img"><img width="240" src="https://doit-prod.s3.amazonaws.com/ED5m6.jpg"></div><h3>劉沛玉</h3><h4 class="exp"><a href="https://www.facebook.com/taiwan.doit">DOIT青年創新平台</a>推動者</h4></div><div class="info"><div class="intro"><p>哲學系畢業，在電視仍只有三家電視台的時代擔任記者，主播，而後加入新創遊戲公司，迎接了萬家爭鳴的網路崛起年代，2005年與夥伴從無毒蝦開始創立無毒食品的事業，目前超過500種商品2008年，加入奧美公關，擁抱創意，並學習知識型服務業的內涵。現今，是DOIT青年創意平台的推動者。</p><p>每一段時間，就想 “動”，想看看世界有多大，可能性有多少，會遇到什麼樣的風景，最棒的是，每一段風景，都會遇到很多精采又值得學習的人，事，物，我想就是這樣，創意才有可能成型，創新才有可能實踐，從“想”到“做”，找到對的人和你一起，共創是人生最美的風景。</p></div></div></div><!-- talker -->'
,'<div class="talker clearfix"><div class="head"><div class="img"><img width="240" src="img/talkers/鋼琴.jpg"></div><h3><a href="https://www.facebook.com/ridepiano">帶著鋼琴去旅行<br>RIDE PIANO</a></h3><h4 class="exp">表演團體</h4></div><div class="info"><p class="stone">「或許我們只是花了人生當中的一小段時間，但我們卻有機會改變別人的一生。」</p><div class="intro"><p>四位在軍中相遇的年輕人，決心將夢想化為行動，把熱血揮灑在音樂與旅行的抑揚頓挫之中，馳騁在關懷弱勢的道路上。</p><p>他們是台灣金曲奬「最佳演奏獎」得主盧易之、最年輕的公司集團設計總監成宗翰、與許多藝人合作過的小提琴家蔡曜宇，以及精通機械的低音號高手簡子毅。他們靠著一股熱誠與對藝術的熱愛，開始在台灣各地寫下無數段美好的旋律。</p></div></div></div><!-- talker -->'] ;
function init (){
	$('.apdArea').on('click','.apdInner',function (e){e.stopPropagation();});
	$('.apdArea').on('click','.apdOuter',function (e){
		$('.apdArea').fadeOut(300,function (){$('.apdArea').empty();});
	});
}

function showTalker(id){
	$talkerApd = $('#talkerApd');
	$talkerApd.append(firstApd);
	$('.apdArea .container').height(h);
	$('.talker_apd').append(talkersArr[id]);
	init ();
	$talkerApd.fadeIn();
}

